import type { Metadata } from 'next'
import { Rokkitt } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from 'react-hot-toast'

const font = Rokkitt({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Place Finder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
    <Toaster />
      <body className={font.className}>
      <Header />
        {children}
      </body>
    </html>
    </ClerkProvider>
  )
}
